package Token.Enums;

public enum EstadosEnum {
    INICIO_LEITURA,
    IGNORAR,
    LIDO_IDENTIFICADOR,
    LIDO_NUMERO_INTEIRO,
    LIDO_NUMERO_REAL_INCOMPLETO,
    LIDO_NUMERO_REAL,
    LIDO_CARACTER_INVALIDO,
    ESTADO_INVALIDO,
    LIDO_LITERAL,
    LIDO_LITERAL_INCOMPLETO,
    LIDO_LITERAL_ERRO,
    LIDO_CARACTER_ESPECIAL,
    LIDO_IDENTIFICADOR_INVALIDO;
}
